models:

  - name: scaled_yolo_v4
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: yolov4-p7.xml
        weights: yolov4-p7.bin
        adapter:
          type: pytorch_yolo
          anchors: 13,17,  22,25,  27,66,  55,41, 57,88,  112,69,  69,177,  136,138, 136,138,  287,114,  134,275,  268,248, 268,248,  232,504,  445,416,  640,640, 812,393,  477,808,  1070,908,  1408,1408
          num: 5
          coords: 4
          classes: 80
          threshold: 0.001
          anchor_masks: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19], ]
          raw_output: True
          outputs:
            - Conv_1050
            - Conv_1066
            - Conv_1082
            - Conv_1098
            - Conv_1114
    datasets:
      - name: ms_coco_detection_80_class_without_background

        preprocessing:
          - type: resize
            size: 1536
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: true
          - type: diou_nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
          - name: AP@0.5
            type: coco_precision
            max_detections: 100
            threshold: 0.5
          - name: AP@0.5:0.05:95
            type: coco_precision
            max_detections: 100
            threshold: '0.5:0.05:0.95'

